### Filebased
# version: '3.4'
# services:
#   cloudflared:
#     image: msnelling/cloudflared
#     container_name: cloudflared
#     env_file:
#       - ../.env
#     volumes:
#       - ./config:/etc/cloudflared
#     # interpolate environment vars into config template to make config and then run
#     command: [sh, -c, ( echo "cat <<EOF" ; cat /etc/cloudflared/config.yml.template ; echo EOF ) | sh > /etc/cloudflared/config.yml && /usr/local/bin/cloudflared tunnel --no-autoupdate run]
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     networks:
#      - cloudflared
#     restart: unless-stopped

# networks:
#   cloudflared:
#     name: cloudflared

### Webbased
version: '3.9'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    environment:
      - TUNNEL_TOKEN=${CLFL_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
     - extnet
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  extnet:
    external: true